In [42]:
import pandas as pd
import numpy as np

# 数据合并 np.concatenate
arr1 = np.random.randint(0, 10, (3,4))
arr2 = np.random.randint(0, 10, (3,4))
print('-'*50)
print(arr1)
print('-'*50)
print(arr2)
print('-'*50)
print(np.concatenate([arr1,arr2]))
print('-'*50)
print(np.concatenate([arr1, arr2], axis = 1))  # 默认为0, 行合并
print('-'*50)

--------------------------------------------------
[[1 1 4 9]
 [1 9 2 6]
 [0 6 6 4]]
--------------------------------------------------
[[0 7 1 9]
 [5 5 9 7]
 [9 7 1 3]]
--------------------------------------------------
[[1 1 4 9]
 [1 9 2 6]
 [0 6 6 4]
 [0 7 1 9]
 [5 5 9 7]
 [9 7 1 3]]
--------------------------------------------------
[[1 1 4 9 0 7 1 9]
 [1 9 2 6 5 5 9 7]
 [0 6 6 4 9 7 1 3]]
--------------------------------------------------


In [43]:
# pd.concat
# 注意指定轴方向，默认axis=0
# join指定合并方式，默认为outer
# Series合并时查看行索引有无重复

# index 没有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(0,5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(5,9))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(9,12))
print('-'*50)
print(ser_obj1)
print('-'*50)
print(ser_obj2)
print('-'*50)
print(ser_obj3)
print('-'*50)
print(pd.concat([ser_obj1, ser_obj2, ser_obj3]))
print('-'*50)
print(pd.concat([ser_obj1, ser_obj2, ser_obj3],axis = 1))
print('-'*50)

--------------------------------------------------
0    9
1    3
2    4
3    2
4    2
dtype: int64
--------------------------------------------------
5    6
6    6
7    8
8    1
dtype: int64
--------------------------------------------------
9     1
10    3
11    8
dtype: int64
--------------------------------------------------
0     9
1     3
2     4
3     2
4     2
5     6
6     6
7     8
8     1
9     1
10    3
11    8
dtype: int64
--------------------------------------------------
      0    1    2
0   9.0  NaN  NaN
1   3.0  NaN  NaN
2   4.0  NaN  NaN
3   2.0  NaN  NaN
4   2.0  NaN  NaN
5   NaN  6.0  NaN
6   NaN  6.0  NaN
7   NaN  8.0  NaN
8   NaN  1.0  NaN
9   NaN  NaN  1.0
10  NaN  NaN  3.0
11  NaN  NaN  8.0
--------------------------------------------------


In [44]:
# index 有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(4))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(3))
print('-'*50)
print(ser_obj1)
print('-'*50)
print(ser_obj2)
print('-'*50)
print(ser_obj3)
print('-'*50)
print(pd.concat([ser_obj1, ser_obj2,ser_obj3]))
print('-'*50)
print(pd.concat([ser_obj1,ser_obj2,ser_obj3],axis=1,join='inner'))  # join='inner' 将去除NaN所在的行或列
print('-'*50)

--------------------------------------------------
0    1
1    7
2    9
3    6
4    8
dtype: int64
--------------------------------------------------
0    7
1    0
2    4
3    5
dtype: int64
--------------------------------------------------
0    1
1    1
2    0
dtype: int64
--------------------------------------------------
0    1
1    7
2    9
3    6
4    8
0    7
1    0
2    4
3    5
0    1
1    1
2    0
dtype: int64
--------------------------------------------------
   0  1  2
0  1  7  1
1  7  0  1
2  9  4  0
--------------------------------------------------


In [45]:
df_obj1 = pd.DataFrame(np.random.randint(0, 10, (3, 2)), index=['a', 'b', 'c'],
                       columns=['A', 'B'])
df_obj2 = pd.DataFrame(np.random.randint(0, 10, (2, 2)), index=['a', 'b'],
                       columns=['C', 'D'])
print('-'*50)
print(df_obj1)
print('-'*50)
print(df_obj2)
print('-'*50)
print(pd.concat([df_obj1, df_obj2]))
print('-'*50)
print(pd.concat([df_obj1, df_obj2], axis=1, join='inner'))
print('-'*50)


--------------------------------------------------
   A  B
a  7  8
b  2  9
c  4  9
--------------------------------------------------
   C  D
a  2  3
b  0  7
--------------------------------------------------
     A    B    C    D
a  7.0  8.0  NaN  NaN
b  2.0  9.0  NaN  NaN
c  4.0  9.0  NaN  NaN
a  NaN  NaN  2.0  3.0
b  NaN  NaN  0.0  7.0
--------------------------------------------------
   A  B  C  D
a  7  8  2  3
b  2  9  0  7
--------------------------------------------------


/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:10: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  # Remove the CWD from sys.path while we load stuff.
