In [1]:
import numpy as np
arr = np.random.rand(3,4)
print(arr)
print(type(arr))

[[0.57814059 0.7049754  0.94819213 0.84504776]
 [0.97333242 0.82633457 0.68590173 0.76083025]
 [0.75456251 0.71536065 0.94883704 0.42803013]]
<class 'numpy.ndarray'>


In [10]:
arr = np.random.randint(-1, 6, size = (3, 4)) # 可以不写 ‘size=’
print(arr)

[[5 2 1 0]
 [3 5 4 0]
 [1 2 3 2]]


In [9]:
arr = np.random.randint(-1, 5, (3, 4))
print(arr)
print("维度个数：", arr.ndim)
print("维度大小：", arr.shape)
print("数据类型：", arr.dtype)

[[ 2  4  2  2]
 [ 4  1 -1  0]
 [ 1 -1 -1  1]]
维度个数： 2
维度大小： (3, 4)
数据类型： int32


In [11]:
arr = np.random.uniform(-1, 5, (3, 4))
print(arr)
print("维度个数：", arr.ndim)
print("维度大小：", arr.shape)
print("数据类型：", arr.dtype)

[[ 2.21803673  0.9407816   4.39452697  4.83967235]
 [-0.84245857  2.30088684  2.40565692 -0.31444543]
 [ 1.01301289  0.37818359  0.69712264 -0.13615582]]
维度个数： 2
维度大小： (3, 4)
数据类型： float64
