In [22]:
import pandas as pd
import numpy as np

ser_obj = pd.Series(range(10))
print(ser_obj)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64


In [16]:
ser_obj =pd.Series(range(10,20))
print(ser_obj)
print(type(ser_obj))

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
<class 'pandas.core.series.Series'>


In [6]:
a,b = ser_obj.index, ser_obj.values
print(a, b)

RangeIndex(start=0, stop=10, step=1) [10 11 12 13 14 15 16 17 18 19]


In [18]:
print(ser_obj[4])
print(ser_obj * 2)
print(ser_obj > 15)


14
0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [14]:
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2.head())
print(ser_obj2.index)

2001    17.8
2002    20.1
2003    16.5
dtype: float64
Int64Index([2001, 2002, 2003], dtype='int64')


In [20]:
ser_obj2.name = "temp"   # 对象名
ser_obj2.index.name = "year"  # 对象索引名
print(ser_obj2.head())

year
2001    17.8
2002    20.1
2003    16.5
Name: temp, dtype: float64


In [24]:
array = np.random.rand(5, 4)  # 通过ndarray将二维数组构建成DataFrame
print(array)

df_obj = pd.DataFrame(array)
print(df_obj)

[[0.27462402 0.67671498 0.9558012  0.8422974 ]
 [0.65459665 0.34199079 0.98623287 0.24055613]
 [0.03274937 0.63767907 0.69821895 0.25224784]
 [0.11624165 0.69123226 0.14376645 0.9078907 ]
 [0.00530212 0.26701549 0.5886552  0.50315284]]
          0         1         2         3
0  0.274624  0.676715  0.955801  0.842297
1  0.654597  0.341991  0.986233  0.240556
2  0.032749  0.637679  0.698219  0.252248
3  0.116242  0.691232  0.143766  0.907891
4  0.005302  0.267015  0.588655  0.503153


In [34]:
dict_data = {'A': 1,  # 通过ndarray将字典构建成DataFrame
             'B': pd.Timestamp('20170426'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([3] * 4,dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'ITCast' }

df_obj2 = pd.DataFrame(dict_data)
print(df_obj2.head())  

# 通过列索引获取数据
print(df_obj2["A"],type(df_obj2["A"]))
print(df_obj2.A)


   A          B    C  D       E       F
0  1 2017-04-26  1.0  3  Python  ITCast
1  1 2017-04-26  1.0  3    Java  ITCast
2  1 2017-04-26  1.0  3     C++  ITCast
3  1 2017-04-26  1.0  3       C  ITCast
0    1
1    1
2    1
3    1
Name: A, dtype: int64 <class 'pandas.core.series.Series'>
0    1
1    1
2    1
3    1
Name: A, dtype: int64


In [36]:
# 添加/删除 一列数据
df_obj2["G"] = df_obj2["D"] + 4
print(df_obj2)

del(df_obj2["G"])
print(df_obj2)


   A          B    C  D       E       F  G
0  1 2017-04-26  1.0  3  Python  ITCast  7
1  1 2017-04-26  1.0  3    Java  ITCast  7
2  1 2017-04-26  1.0  3     C++  ITCast  7
3  1 2017-04-26  1.0  3       C  ITCast  7
   A          B    C  D       E       F
0  1 2017-04-26  1.0  3  Python  ITCast
1  1 2017-04-26  1.0  3    Java  ITCast
2  1 2017-04-26  1.0  3     C++  ITCast
3  1 2017-04-26  1.0  3       C  ITCast


In [37]:
# Series和DataFrame中的索引都是Index对象
print(type(ser_obj.index))
print(type(df_obj2.index))

print(df_obj2.index)

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'pandas.core.indexes.numeric.Int64Index'>
Int64Index([0, 1, 2, 3], dtype='int64')


In [38]:
# 索引对象不可变，保证了数据的安全
df_obj.index[0] = 2

TypeError: Index does not support mutable operations

In [39]:
ser_obj = pd.Series(range(5), index = ['a', 'b', 'c', 'd', 'e'])
print(ser_obj.head())

a    0
b    1
c    2
d    3
e    4
dtype: int64


In [40]:
print(ser_obj['b'])  # index对应的值
print(ser_obj[2])  # 值对应的index

1
2


In [43]:
print(ser_obj[1:3])
print(ser_obj['b':'d'])  # 按索引名切片操作时，是包含终止索引的。

b    1
c    2
dtype: int64
b    1
c    2
d    3
dtype: int64


In [44]:
# 不连续索引
print(ser_obj[[0, 2, 4]])
print(ser_obj[['a', 'e']])

a    0
c    2
e    4
dtype: int64
a    0
e    4
dtype: int64


In [5]:
# 布尔索引
ser_bool = ser_obj > 2
print(ser_bool)
print(ser_obj[ser_bool])
print(ser_obj[ser_obj > 2])

NameError: name 'ser_obj' is not defined

In [6]:
import pandas as pd
import numpy as np

df_obj = pd.DataFrame(np.random.rand(5,4), columns = ["a", "b", "c", "d"])
print(df_obj.head())

          a         b         c         d
0  0.406372  0.145264  0.453454  0.641631
1  0.840055  0.862629  0.163285  0.951438
2  0.213627  0.418755  0.109260  0.220036
3  0.860865  0.710581  0.109999  0.813026
4  0.017804  0.998506  0.379731  0.545168
